server:
  port: ${SERVER_PORT:8081}
spring:
  profiles:
    active: dev
  data:
    redis:
      host: redis-demo
      port: 6379
      timeout: 5000
  datasource:
    url: jdbc:mysql://mysql-demo:3306/ai_system
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true